[package]
name = "Volume_Tool"
version = "0.1.0"
edition = "2021"

[dependencies]
kucoin_rs = { git = "https://github.com/escwdev/kucoin_rs", branch = "master" }
tokio = {version = "1.28.0", features = ["full"]}
futures-util = "0.3.21"
failure = "0.1"
